#!/bin/bash -ex

# Install script for couchbase-single-server.
#
# You can use this script as a CloudInit "#include" file on Amazon EC2.
# The Default Amazon Linux AMI, for example, is CloudInit-capapble...
#
#   Basic 64-bit Amazon Linux AMI 2011.02.1 Beta (AMI Id: ami-8e1fece7)
#
# When launching your EC2 instance, specify a UserData of...
#
#   #include
#   https://raw.github.com/couchbaselabs/cloud-init/master/couchbase-single-server-community_x86_64_2.0.0-dev-preview-3.rpm.install
#
COUCHBASE_PASSWORD=password

yum -y install openssl098e

wget http://files.couchbase.com/developer-previews/couchbase-single-server-2.0.0-dev-preview/couchbase-single-server-community_x86_64_2.0.0-dev-preview-3.rpm

rpm -i couchbase-single-server-community*.rpm

curl -X PUT http://127.0.0.1:5984/_config/admins/admin -d \"${COUCHBASE_PASSWORD}\"

# At this point, Couchbase Single Server will be running but only
# listening on address 127.0.0.1.  To fix this, change the
# /opt/couchbase/etc/couchdb/local.ini bind_address to 0.0.0.0 to
# allow remote web access.

